# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_auto_20170424_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(default='Other', max_length=255),
            preserve_default=False,
        ),
    ]
